/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as OwnerRouteRouteImport } from './routes/owner/route'
import { Route as GymPortalRouteRouteImport } from './routes/gym-portal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerDashboardRouteImport } from './routes/owner/dashboard'
import { Route as OwnerConsoleRouteImport } from './routes/owner/console'
import { Route as GymPortalSignupRouteImport } from './routes/gym-portal/signup'
import { Route as GymPortalSetupRouteImport } from './routes/gym-portal/setup'
import { Route as GymPortalLoginRouteImport } from './routes/gym-portal/login'
import { Route as GymGymSlugRouteRouteImport } from './routes/gym/$gymSlug/route'
import { Route as GymGymSlugIndexRouteImport } from './routes/gym/$gymSlug/index'
import { Route as GymGymSlugStaffLoginRouteImport } from './routes/gym/$gymSlug/staff-login'
import { Route as GymGymSlugSignupRouteImport } from './routes/gym/$gymSlug/signup'
import { Route as GymGymSlugResetPasswordRouteImport } from './routes/gym/$gymSlug/reset-password'
import { Route as GymGymSlugOnboardingRouteImport } from './routes/gym/$gymSlug/onboarding'
import { Route as GymGymSlugForgotRouteImport } from './routes/gym/$gymSlug/forgot'
import { Route as GymGymSlugAuthRouteImport } from './routes/gym/$gymSlug/auth'
import { Route as GymGymSlugAdminRouteImport } from './routes/gym/$gymSlug/admin'
import { Route as GymGymSlugAppRouteImport } from './routes/gym/$gymSlug/_app'
import { Route as GymGymSlugAppProfileRouteImport } from './routes/gym/$gymSlug/_app/profile'
import { Route as GymGymSlugAppNewsRouteImport } from './routes/gym/$gymSlug/_app/news'
import { Route as GymGymSlugAppMembershipRouteImport } from './routes/gym/$gymSlug/_app/membership'
import { Route as GymGymSlugAppLocationRouteImport } from './routes/gym/$gymSlug/_app/location'
import { Route as GymGymSlugAppHomeRouteImport } from './routes/gym/$gymSlug/_app/home'
import { Route as GymGymSlugAppCoachesRouteImport } from './routes/gym/$gymSlug/_app/coaches'
import { Route as GymGymSlugAppBookRouteImport } from './routes/gym/$gymSlug/_app/book'
import { Route as GymGymSlugAppProfileIndexRouteImport } from './routes/gym/$gymSlug/_app/profile.index'
import { Route as GymGymSlugAdminMembersIdRouteImport } from './routes/gym/$gymSlug/admin.members.$id'
import { Route as GymGymSlugAppProfileSettingsRouteImport } from './routes/gym/$gymSlug/_app/profile.settings'
import { Route as GymGymSlugAppProfileReferralRouteImport } from './routes/gym/$gymSlug/_app/profile.referral'
import { Route as GymGymSlugAppProfileEditRouteImport } from './routes/gym/$gymSlug/_app/profile.edit'
import { Route as GymGymSlugAppProfileChildrenRouteImport } from './routes/gym/$gymSlug/_app/profile.children'
import { Route as GymGymSlugAppProfileBookingsRouteImport } from './routes/gym/$gymSlug/_app/profile.bookings'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRouteRoute = OwnerRouteRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const GymPortalRouteRoute = GymPortalRouteRouteImport.update({
  id: '/gym-portal',
  path: '/gym-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerConsoleRoute = OwnerConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const GymPortalSignupRoute = GymPortalSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GymPortalRouteRoute,
} as any)
const GymPortalSetupRoute = GymPortalSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => GymPortalRouteRoute,
} as any)
const GymPortalLoginRoute = GymPortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GymPortalRouteRoute,
} as any)
const GymGymSlugRouteRoute = GymGymSlugRouteRouteImport.update({
  id: '/gym/$gymSlug',
  path: '/gym/$gymSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GymGymSlugIndexRoute = GymGymSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GymGymSlugRouteRoute,
} as any)
const GymGymSlugStaffLoginRoute = GymGymSlugStaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => GymGymSlugRouteRoute,
} as any)
const GymGymSlugSignupRoute = GymGymSlugSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GymGymSlugRouteRoute,
} as any)
const GymGymSlugResetPasswordRoute = GymGymSlugResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GymGymSlugRouteRoute,
} as any)
const GymGymSlugOnboardingRoute = GymGymSlugOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => GymGymSlugRouteRoute,
} as any)
const GymGymSlugForgotRoute = GymGymSlugForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => GymGymSlugRouteRoute,
} as any)
const GymGymSlugAuthRoute = GymGymSlugAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => GymGymSlugRouteRoute,
} as any)
const GymGymSlugAdminRoute = GymGymSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => GymGymSlugRouteRoute,
} as any)
const GymGymSlugAppRoute = GymGymSlugAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => GymGymSlugRouteRoute,
} as any)
const GymGymSlugAppProfileRoute = GymGymSlugAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GymGymSlugAppRoute,
} as any)
const GymGymSlugAppNewsRoute = GymGymSlugAppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => GymGymSlugAppRoute,
} as any)
const GymGymSlugAppMembershipRoute = GymGymSlugAppMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => GymGymSlugAppRoute,
} as any)
const GymGymSlugAppLocationRoute = GymGymSlugAppLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => GymGymSlugAppRoute,
} as any)
const GymGymSlugAppHomeRoute = GymGymSlugAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => GymGymSlugAppRoute,
} as any)
const GymGymSlugAppCoachesRoute = GymGymSlugAppCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => GymGymSlugAppRoute,
} as any)
const GymGymSlugAppBookRoute = GymGymSlugAppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => GymGymSlugAppRoute,
} as any)
const GymGymSlugAppProfileIndexRoute =
  GymGymSlugAppProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GymGymSlugAppProfileRoute,
  } as any)
const GymGymSlugAdminMembersIdRoute =
  GymGymSlugAdminMembersIdRouteImport.update({
    id: '/members/$id',
    path: '/members/$id',
    getParentRoute: () => GymGymSlugAdminRoute,
  } as any)
const GymGymSlugAppProfileSettingsRoute =
  GymGymSlugAppProfileSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => GymGymSlugAppProfileRoute,
  } as any)
const GymGymSlugAppProfileReferralRoute =
  GymGymSlugAppProfileReferralRouteImport.update({
    id: '/referral',
    path: '/referral',
    getParentRoute: () => GymGymSlugAppProfileRoute,
  } as any)
const GymGymSlugAppProfileEditRoute =
  GymGymSlugAppProfileEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => GymGymSlugAppProfileRoute,
  } as any)
const GymGymSlugAppProfileChildrenRoute =
  GymGymSlugAppProfileChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => GymGymSlugAppProfileRoute,
  } as any)
const GymGymSlugAppProfileBookingsRoute =
  GymGymSlugAppProfileBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => GymGymSlugAppProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gym-portal': typeof GymPortalRouteRouteWithChildren
  '/owner': typeof OwnerRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/gym/$gymSlug': typeof GymGymSlugRouteRouteWithChildren
  '/gym-portal/login': typeof GymPortalLoginRoute
  '/gym-portal/setup': typeof GymPortalSetupRoute
  '/gym-portal/signup': typeof GymPortalSignupRoute
  '/owner/console': typeof OwnerConsoleRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/gym/$gymSlug/admin': typeof GymGymSlugAdminRouteWithChildren
  '/gym/$gymSlug/auth': typeof GymGymSlugAuthRoute
  '/gym/$gymSlug/forgot': typeof GymGymSlugForgotRoute
  '/gym/$gymSlug/onboarding': typeof GymGymSlugOnboardingRoute
  '/gym/$gymSlug/reset-password': typeof GymGymSlugResetPasswordRoute
  '/gym/$gymSlug/signup': typeof GymGymSlugSignupRoute
  '/gym/$gymSlug/staff-login': typeof GymGymSlugStaffLoginRoute
  '/gym/$gymSlug/': typeof GymGymSlugIndexRoute
  '/gym/$gymSlug/book': typeof GymGymSlugAppBookRoute
  '/gym/$gymSlug/coaches': typeof GymGymSlugAppCoachesRoute
  '/gym/$gymSlug/home': typeof GymGymSlugAppHomeRoute
  '/gym/$gymSlug/location': typeof GymGymSlugAppLocationRoute
  '/gym/$gymSlug/membership': typeof GymGymSlugAppMembershipRoute
  '/gym/$gymSlug/news': typeof GymGymSlugAppNewsRoute
  '/gym/$gymSlug/profile': typeof GymGymSlugAppProfileRouteWithChildren
  '/gym/$gymSlug/profile/bookings': typeof GymGymSlugAppProfileBookingsRoute
  '/gym/$gymSlug/profile/children': typeof GymGymSlugAppProfileChildrenRoute
  '/gym/$gymSlug/profile/edit': typeof GymGymSlugAppProfileEditRoute
  '/gym/$gymSlug/profile/referral': typeof GymGymSlugAppProfileReferralRoute
  '/gym/$gymSlug/profile/settings': typeof GymGymSlugAppProfileSettingsRoute
  '/gym/$gymSlug/admin/members/$id': typeof GymGymSlugAdminMembersIdRoute
  '/gym/$gymSlug/profile/': typeof GymGymSlugAppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gym-portal': typeof GymPortalRouteRouteWithChildren
  '/owner': typeof OwnerRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/gym-portal/login': typeof GymPortalLoginRoute
  '/gym-portal/setup': typeof GymPortalSetupRoute
  '/gym-portal/signup': typeof GymPortalSignupRoute
  '/owner/console': typeof OwnerConsoleRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/gym/$gymSlug': typeof GymGymSlugIndexRoute
  '/gym/$gymSlug/admin': typeof GymGymSlugAdminRouteWithChildren
  '/gym/$gymSlug/auth': typeof GymGymSlugAuthRoute
  '/gym/$gymSlug/forgot': typeof GymGymSlugForgotRoute
  '/gym/$gymSlug/onboarding': typeof GymGymSlugOnboardingRoute
  '/gym/$gymSlug/reset-password': typeof GymGymSlugResetPasswordRoute
  '/gym/$gymSlug/signup': typeof GymGymSlugSignupRoute
  '/gym/$gymSlug/staff-login': typeof GymGymSlugStaffLoginRoute
  '/gym/$gymSlug/book': typeof GymGymSlugAppBookRoute
  '/gym/$gymSlug/coaches': typeof GymGymSlugAppCoachesRoute
  '/gym/$gymSlug/home': typeof GymGymSlugAppHomeRoute
  '/gym/$gymSlug/location': typeof GymGymSlugAppLocationRoute
  '/gym/$gymSlug/membership': typeof GymGymSlugAppMembershipRoute
  '/gym/$gymSlug/news': typeof GymGymSlugAppNewsRoute
  '/gym/$gymSlug/profile/bookings': typeof GymGymSlugAppProfileBookingsRoute
  '/gym/$gymSlug/profile/children': typeof GymGymSlugAppProfileChildrenRoute
  '/gym/$gymSlug/profile/edit': typeof GymGymSlugAppProfileEditRoute
  '/gym/$gymSlug/profile/referral': typeof GymGymSlugAppProfileReferralRoute
  '/gym/$gymSlug/profile/settings': typeof GymGymSlugAppProfileSettingsRoute
  '/gym/$gymSlug/admin/members/$id': typeof GymGymSlugAdminMembersIdRoute
  '/gym/$gymSlug/profile': typeof GymGymSlugAppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gym-portal': typeof GymPortalRouteRouteWithChildren
  '/owner': typeof OwnerRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/gym/$gymSlug': typeof GymGymSlugRouteRouteWithChildren
  '/gym-portal/login': typeof GymPortalLoginRoute
  '/gym-portal/setup': typeof GymPortalSetupRoute
  '/gym-portal/signup': typeof GymPortalSignupRoute
  '/owner/console': typeof OwnerConsoleRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/gym/$gymSlug/_app': typeof GymGymSlugAppRouteWithChildren
  '/gym/$gymSlug/admin': typeof GymGymSlugAdminRouteWithChildren
  '/gym/$gymSlug/auth': typeof GymGymSlugAuthRoute
  '/gym/$gymSlug/forgot': typeof GymGymSlugForgotRoute
  '/gym/$gymSlug/onboarding': typeof GymGymSlugOnboardingRoute
  '/gym/$gymSlug/reset-password': typeof GymGymSlugResetPasswordRoute
  '/gym/$gymSlug/signup': typeof GymGymSlugSignupRoute
  '/gym/$gymSlug/staff-login': typeof GymGymSlugStaffLoginRoute
  '/gym/$gymSlug/': typeof GymGymSlugIndexRoute
  '/gym/$gymSlug/_app/book': typeof GymGymSlugAppBookRoute
  '/gym/$gymSlug/_app/coaches': typeof GymGymSlugAppCoachesRoute
  '/gym/$gymSlug/_app/home': typeof GymGymSlugAppHomeRoute
  '/gym/$gymSlug/_app/location': typeof GymGymSlugAppLocationRoute
  '/gym/$gymSlug/_app/membership': typeof GymGymSlugAppMembershipRoute
  '/gym/$gymSlug/_app/news': typeof GymGymSlugAppNewsRoute
  '/gym/$gymSlug/_app/profile': typeof GymGymSlugAppProfileRouteWithChildren
  '/gym/$gymSlug/_app/profile/bookings': typeof GymGymSlugAppProfileBookingsRoute
  '/gym/$gymSlug/_app/profile/children': typeof GymGymSlugAppProfileChildrenRoute
  '/gym/$gymSlug/_app/profile/edit': typeof GymGymSlugAppProfileEditRoute
  '/gym/$gymSlug/_app/profile/referral': typeof GymGymSlugAppProfileReferralRoute
  '/gym/$gymSlug/_app/profile/settings': typeof GymGymSlugAppProfileSettingsRoute
  '/gym/$gymSlug/admin/members/$id': typeof GymGymSlugAdminMembersIdRoute
  '/gym/$gymSlug/_app/profile/': typeof GymGymSlugAppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gym-portal'
    | '/owner'
    | '/$'
    | '/gym/$gymSlug'
    | '/gym-portal/login'
    | '/gym-portal/setup'
    | '/gym-portal/signup'
    | '/owner/console'
    | '/owner/dashboard'
    | '/gym/$gymSlug/admin'
    | '/gym/$gymSlug/auth'
    | '/gym/$gymSlug/forgot'
    | '/gym/$gymSlug/onboarding'
    | '/gym/$gymSlug/reset-password'
    | '/gym/$gymSlug/signup'
    | '/gym/$gymSlug/staff-login'
    | '/gym/$gymSlug/'
    | '/gym/$gymSlug/book'
    | '/gym/$gymSlug/coaches'
    | '/gym/$gymSlug/home'
    | '/gym/$gymSlug/location'
    | '/gym/$gymSlug/membership'
    | '/gym/$gymSlug/news'
    | '/gym/$gymSlug/profile'
    | '/gym/$gymSlug/profile/bookings'
    | '/gym/$gymSlug/profile/children'
    | '/gym/$gymSlug/profile/edit'
    | '/gym/$gymSlug/profile/referral'
    | '/gym/$gymSlug/profile/settings'
    | '/gym/$gymSlug/admin/members/$id'
    | '/gym/$gymSlug/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gym-portal'
    | '/owner'
    | '/$'
    | '/gym-portal/login'
    | '/gym-portal/setup'
    | '/gym-portal/signup'
    | '/owner/console'
    | '/owner/dashboard'
    | '/gym/$gymSlug'
    | '/gym/$gymSlug/admin'
    | '/gym/$gymSlug/auth'
    | '/gym/$gymSlug/forgot'
    | '/gym/$gymSlug/onboarding'
    | '/gym/$gymSlug/reset-password'
    | '/gym/$gymSlug/signup'
    | '/gym/$gymSlug/staff-login'
    | '/gym/$gymSlug/book'
    | '/gym/$gymSlug/coaches'
    | '/gym/$gymSlug/home'
    | '/gym/$gymSlug/location'
    | '/gym/$gymSlug/membership'
    | '/gym/$gymSlug/news'
    | '/gym/$gymSlug/profile/bookings'
    | '/gym/$gymSlug/profile/children'
    | '/gym/$gymSlug/profile/edit'
    | '/gym/$gymSlug/profile/referral'
    | '/gym/$gymSlug/profile/settings'
    | '/gym/$gymSlug/admin/members/$id'
    | '/gym/$gymSlug/profile'
  id:
    | '__root__'
    | '/'
    | '/gym-portal'
    | '/owner'
    | '/$'
    | '/gym/$gymSlug'
    | '/gym-portal/login'
    | '/gym-portal/setup'
    | '/gym-portal/signup'
    | '/owner/console'
    | '/owner/dashboard'
    | '/gym/$gymSlug/_app'
    | '/gym/$gymSlug/admin'
    | '/gym/$gymSlug/auth'
    | '/gym/$gymSlug/forgot'
    | '/gym/$gymSlug/onboarding'
    | '/gym/$gymSlug/reset-password'
    | '/gym/$gymSlug/signup'
    | '/gym/$gymSlug/staff-login'
    | '/gym/$gymSlug/'
    | '/gym/$gymSlug/_app/book'
    | '/gym/$gymSlug/_app/coaches'
    | '/gym/$gymSlug/_app/home'
    | '/gym/$gymSlug/_app/location'
    | '/gym/$gymSlug/_app/membership'
    | '/gym/$gymSlug/_app/news'
    | '/gym/$gymSlug/_app/profile'
    | '/gym/$gymSlug/_app/profile/bookings'
    | '/gym/$gymSlug/_app/profile/children'
    | '/gym/$gymSlug/_app/profile/edit'
    | '/gym/$gymSlug/_app/profile/referral'
    | '/gym/$gymSlug/_app/profile/settings'
    | '/gym/$gymSlug/admin/members/$id'
    | '/gym/$gymSlug/_app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GymPortalRouteRoute: typeof GymPortalRouteRouteWithChildren
  OwnerRouteRoute: typeof OwnerRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  GymGymSlugRouteRoute: typeof GymGymSlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym-portal': {
      id: '/gym-portal'
      path: '/gym-portal'
      fullPath: '/gym-portal'
      preLoaderRoute: typeof GymPortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/owner/console': {
      id: '/owner/console'
      path: '/console'
      fullPath: '/owner/console'
      preLoaderRoute: typeof OwnerConsoleRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/gym-portal/signup': {
      id: '/gym-portal/signup'
      path: '/signup'
      fullPath: '/gym-portal/signup'
      preLoaderRoute: typeof GymPortalSignupRouteImport
      parentRoute: typeof GymPortalRouteRoute
    }
    '/gym-portal/setup': {
      id: '/gym-portal/setup'
      path: '/setup'
      fullPath: '/gym-portal/setup'
      preLoaderRoute: typeof GymPortalSetupRouteImport
      parentRoute: typeof GymPortalRouteRoute
    }
    '/gym-portal/login': {
      id: '/gym-portal/login'
      path: '/login'
      fullPath: '/gym-portal/login'
      preLoaderRoute: typeof GymPortalLoginRouteImport
      parentRoute: typeof GymPortalRouteRoute
    }
    '/gym/$gymSlug': {
      id: '/gym/$gymSlug'
      path: '/gym/$gymSlug'
      fullPath: '/gym/$gymSlug'
      preLoaderRoute: typeof GymGymSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/$gymSlug/': {
      id: '/gym/$gymSlug/'
      path: '/'
      fullPath: '/gym/$gymSlug/'
      preLoaderRoute: typeof GymGymSlugIndexRouteImport
      parentRoute: typeof GymGymSlugRouteRoute
    }
    '/gym/$gymSlug/staff-login': {
      id: '/gym/$gymSlug/staff-login'
      path: '/staff-login'
      fullPath: '/gym/$gymSlug/staff-login'
      preLoaderRoute: typeof GymGymSlugStaffLoginRouteImport
      parentRoute: typeof GymGymSlugRouteRoute
    }
    '/gym/$gymSlug/signup': {
      id: '/gym/$gymSlug/signup'
      path: '/signup'
      fullPath: '/gym/$gymSlug/signup'
      preLoaderRoute: typeof GymGymSlugSignupRouteImport
      parentRoute: typeof GymGymSlugRouteRoute
    }
    '/gym/$gymSlug/reset-password': {
      id: '/gym/$gymSlug/reset-password'
      path: '/reset-password'
      fullPath: '/gym/$gymSlug/reset-password'
      preLoaderRoute: typeof GymGymSlugResetPasswordRouteImport
      parentRoute: typeof GymGymSlugRouteRoute
    }
    '/gym/$gymSlug/onboarding': {
      id: '/gym/$gymSlug/onboarding'
      path: '/onboarding'
      fullPath: '/gym/$gymSlug/onboarding'
      preLoaderRoute: typeof GymGymSlugOnboardingRouteImport
      parentRoute: typeof GymGymSlugRouteRoute
    }
    '/gym/$gymSlug/forgot': {
      id: '/gym/$gymSlug/forgot'
      path: '/forgot'
      fullPath: '/gym/$gymSlug/forgot'
      preLoaderRoute: typeof GymGymSlugForgotRouteImport
      parentRoute: typeof GymGymSlugRouteRoute
    }
    '/gym/$gymSlug/auth': {
      id: '/gym/$gymSlug/auth'
      path: '/auth'
      fullPath: '/gym/$gymSlug/auth'
      preLoaderRoute: typeof GymGymSlugAuthRouteImport
      parentRoute: typeof GymGymSlugRouteRoute
    }
    '/gym/$gymSlug/admin': {
      id: '/gym/$gymSlug/admin'
      path: '/admin'
      fullPath: '/gym/$gymSlug/admin'
      preLoaderRoute: typeof GymGymSlugAdminRouteImport
      parentRoute: typeof GymGymSlugRouteRoute
    }
    '/gym/$gymSlug/_app': {
      id: '/gym/$gymSlug/_app'
      path: ''
      fullPath: '/gym/$gymSlug'
      preLoaderRoute: typeof GymGymSlugAppRouteImport
      parentRoute: typeof GymGymSlugRouteRoute
    }
    '/gym/$gymSlug/_app/profile': {
      id: '/gym/$gymSlug/_app/profile'
      path: '/profile'
      fullPath: '/gym/$gymSlug/profile'
      preLoaderRoute: typeof GymGymSlugAppProfileRouteImport
      parentRoute: typeof GymGymSlugAppRoute
    }
    '/gym/$gymSlug/_app/news': {
      id: '/gym/$gymSlug/_app/news'
      path: '/news'
      fullPath: '/gym/$gymSlug/news'
      preLoaderRoute: typeof GymGymSlugAppNewsRouteImport
      parentRoute: typeof GymGymSlugAppRoute
    }
    '/gym/$gymSlug/_app/membership': {
      id: '/gym/$gymSlug/_app/membership'
      path: '/membership'
      fullPath: '/gym/$gymSlug/membership'
      preLoaderRoute: typeof GymGymSlugAppMembershipRouteImport
      parentRoute: typeof GymGymSlugAppRoute
    }
    '/gym/$gymSlug/_app/location': {
      id: '/gym/$gymSlug/_app/location'
      path: '/location'
      fullPath: '/gym/$gymSlug/location'
      preLoaderRoute: typeof GymGymSlugAppLocationRouteImport
      parentRoute: typeof GymGymSlugAppRoute
    }
    '/gym/$gymSlug/_app/home': {
      id: '/gym/$gymSlug/_app/home'
      path: '/home'
      fullPath: '/gym/$gymSlug/home'
      preLoaderRoute: typeof GymGymSlugAppHomeRouteImport
      parentRoute: typeof GymGymSlugAppRoute
    }
    '/gym/$gymSlug/_app/coaches': {
      id: '/gym/$gymSlug/_app/coaches'
      path: '/coaches'
      fullPath: '/gym/$gymSlug/coaches'
      preLoaderRoute: typeof GymGymSlugAppCoachesRouteImport
      parentRoute: typeof GymGymSlugAppRoute
    }
    '/gym/$gymSlug/_app/book': {
      id: '/gym/$gymSlug/_app/book'
      path: '/book'
      fullPath: '/gym/$gymSlug/book'
      preLoaderRoute: typeof GymGymSlugAppBookRouteImport
      parentRoute: typeof GymGymSlugAppRoute
    }
    '/gym/$gymSlug/_app/profile/': {
      id: '/gym/$gymSlug/_app/profile/'
      path: '/'
      fullPath: '/gym/$gymSlug/profile/'
      preLoaderRoute: typeof GymGymSlugAppProfileIndexRouteImport
      parentRoute: typeof GymGymSlugAppProfileRoute
    }
    '/gym/$gymSlug/admin/members/$id': {
      id: '/gym/$gymSlug/admin/members/$id'
      path: '/members/$id'
      fullPath: '/gym/$gymSlug/admin/members/$id'
      preLoaderRoute: typeof GymGymSlugAdminMembersIdRouteImport
      parentRoute: typeof GymGymSlugAdminRoute
    }
    '/gym/$gymSlug/_app/profile/settings': {
      id: '/gym/$gymSlug/_app/profile/settings'
      path: '/settings'
      fullPath: '/gym/$gymSlug/profile/settings'
      preLoaderRoute: typeof GymGymSlugAppProfileSettingsRouteImport
      parentRoute: typeof GymGymSlugAppProfileRoute
    }
    '/gym/$gymSlug/_app/profile/referral': {
      id: '/gym/$gymSlug/_app/profile/referral'
      path: '/referral'
      fullPath: '/gym/$gymSlug/profile/referral'
      preLoaderRoute: typeof GymGymSlugAppProfileReferralRouteImport
      parentRoute: typeof GymGymSlugAppProfileRoute
    }
    '/gym/$gymSlug/_app/profile/edit': {
      id: '/gym/$gymSlug/_app/profile/edit'
      path: '/edit'
      fullPath: '/gym/$gymSlug/profile/edit'
      preLoaderRoute: typeof GymGymSlugAppProfileEditRouteImport
      parentRoute: typeof GymGymSlugAppProfileRoute
    }
    '/gym/$gymSlug/_app/profile/children': {
      id: '/gym/$gymSlug/_app/profile/children'
      path: '/children'
      fullPath: '/gym/$gymSlug/profile/children'
      preLoaderRoute: typeof GymGymSlugAppProfileChildrenRouteImport
      parentRoute: typeof GymGymSlugAppProfileRoute
    }
    '/gym/$gymSlug/_app/profile/bookings': {
      id: '/gym/$gymSlug/_app/profile/bookings'
      path: '/bookings'
      fullPath: '/gym/$gymSlug/profile/bookings'
      preLoaderRoute: typeof GymGymSlugAppProfileBookingsRouteImport
      parentRoute: typeof GymGymSlugAppProfileRoute
    }
  }
}

interface GymPortalRouteRouteChildren {
  GymPortalLoginRoute: typeof GymPortalLoginRoute
  GymPortalSetupRoute: typeof GymPortalSetupRoute
  GymPortalSignupRoute: typeof GymPortalSignupRoute
}

const GymPortalRouteRouteChildren: GymPortalRouteRouteChildren = {
  GymPortalLoginRoute: GymPortalLoginRoute,
  GymPortalSetupRoute: GymPortalSetupRoute,
  GymPortalSignupRoute: GymPortalSignupRoute,
}

const GymPortalRouteRouteWithChildren = GymPortalRouteRoute._addFileChildren(
  GymPortalRouteRouteChildren,
)

interface OwnerRouteRouteChildren {
  OwnerConsoleRoute: typeof OwnerConsoleRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
}

const OwnerRouteRouteChildren: OwnerRouteRouteChildren = {
  OwnerConsoleRoute: OwnerConsoleRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
}

const OwnerRouteRouteWithChildren = OwnerRouteRoute._addFileChildren(
  OwnerRouteRouteChildren,
)

interface GymGymSlugAppProfileRouteChildren {
  GymGymSlugAppProfileBookingsRoute: typeof GymGymSlugAppProfileBookingsRoute
  GymGymSlugAppProfileChildrenRoute: typeof GymGymSlugAppProfileChildrenRoute
  GymGymSlugAppProfileEditRoute: typeof GymGymSlugAppProfileEditRoute
  GymGymSlugAppProfileReferralRoute: typeof GymGymSlugAppProfileReferralRoute
  GymGymSlugAppProfileSettingsRoute: typeof GymGymSlugAppProfileSettingsRoute
  GymGymSlugAppProfileIndexRoute: typeof GymGymSlugAppProfileIndexRoute
}

const GymGymSlugAppProfileRouteChildren: GymGymSlugAppProfileRouteChildren = {
  GymGymSlugAppProfileBookingsRoute: GymGymSlugAppProfileBookingsRoute,
  GymGymSlugAppProfileChildrenRoute: GymGymSlugAppProfileChildrenRoute,
  GymGymSlugAppProfileEditRoute: GymGymSlugAppProfileEditRoute,
  GymGymSlugAppProfileReferralRoute: GymGymSlugAppProfileReferralRoute,
  GymGymSlugAppProfileSettingsRoute: GymGymSlugAppProfileSettingsRoute,
  GymGymSlugAppProfileIndexRoute: GymGymSlugAppProfileIndexRoute,
}

const GymGymSlugAppProfileRouteWithChildren =
  GymGymSlugAppProfileRoute._addFileChildren(GymGymSlugAppProfileRouteChildren)

interface GymGymSlugAppRouteChildren {
  GymGymSlugAppBookRoute: typeof GymGymSlugAppBookRoute
  GymGymSlugAppCoachesRoute: typeof GymGymSlugAppCoachesRoute
  GymGymSlugAppHomeRoute: typeof GymGymSlugAppHomeRoute
  GymGymSlugAppLocationRoute: typeof GymGymSlugAppLocationRoute
  GymGymSlugAppMembershipRoute: typeof GymGymSlugAppMembershipRoute
  GymGymSlugAppNewsRoute: typeof GymGymSlugAppNewsRoute
  GymGymSlugAppProfileRoute: typeof GymGymSlugAppProfileRouteWithChildren
}

const GymGymSlugAppRouteChildren: GymGymSlugAppRouteChildren = {
  GymGymSlugAppBookRoute: GymGymSlugAppBookRoute,
  GymGymSlugAppCoachesRoute: GymGymSlugAppCoachesRoute,
  GymGymSlugAppHomeRoute: GymGymSlugAppHomeRoute,
  GymGymSlugAppLocationRoute: GymGymSlugAppLocationRoute,
  GymGymSlugAppMembershipRoute: GymGymSlugAppMembershipRoute,
  GymGymSlugAppNewsRoute: GymGymSlugAppNewsRoute,
  GymGymSlugAppProfileRoute: GymGymSlugAppProfileRouteWithChildren,
}

const GymGymSlugAppRouteWithChildren = GymGymSlugAppRoute._addFileChildren(
  GymGymSlugAppRouteChildren,
)

interface GymGymSlugAdminRouteChildren {
  GymGymSlugAdminMembersIdRoute: typeof GymGymSlugAdminMembersIdRoute
}

const GymGymSlugAdminRouteChildren: GymGymSlugAdminRouteChildren = {
  GymGymSlugAdminMembersIdRoute: GymGymSlugAdminMembersIdRoute,
}

const GymGymSlugAdminRouteWithChildren = GymGymSlugAdminRoute._addFileChildren(
  GymGymSlugAdminRouteChildren,
)

interface GymGymSlugRouteRouteChildren {
  GymGymSlugAppRoute: typeof GymGymSlugAppRouteWithChildren
  GymGymSlugAdminRoute: typeof GymGymSlugAdminRouteWithChildren
  GymGymSlugAuthRoute: typeof GymGymSlugAuthRoute
  GymGymSlugForgotRoute: typeof GymGymSlugForgotRoute
  GymGymSlugOnboardingRoute: typeof GymGymSlugOnboardingRoute
  GymGymSlugResetPasswordRoute: typeof GymGymSlugResetPasswordRoute
  GymGymSlugSignupRoute: typeof GymGymSlugSignupRoute
  GymGymSlugStaffLoginRoute: typeof GymGymSlugStaffLoginRoute
  GymGymSlugIndexRoute: typeof GymGymSlugIndexRoute
}

const GymGymSlugRouteRouteChildren: GymGymSlugRouteRouteChildren = {
  GymGymSlugAppRoute: GymGymSlugAppRouteWithChildren,
  GymGymSlugAdminRoute: GymGymSlugAdminRouteWithChildren,
  GymGymSlugAuthRoute: GymGymSlugAuthRoute,
  GymGymSlugForgotRoute: GymGymSlugForgotRoute,
  GymGymSlugOnboardingRoute: GymGymSlugOnboardingRoute,
  GymGymSlugResetPasswordRoute: GymGymSlugResetPasswordRoute,
  GymGymSlugSignupRoute: GymGymSlugSignupRoute,
  GymGymSlugStaffLoginRoute: GymGymSlugStaffLoginRoute,
  GymGymSlugIndexRoute: GymGymSlugIndexRoute,
}

const GymGymSlugRouteRouteWithChildren = GymGymSlugRouteRoute._addFileChildren(
  GymGymSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GymPortalRouteRoute: GymPortalRouteRouteWithChildren,
  OwnerRouteRoute: OwnerRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  GymGymSlugRouteRoute: GymGymSlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
