/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformSignupRouteImport } from './routes/platform/signup'
import { Route as PlatformSetupRouteImport } from './routes/platform/setup'
import { Route as PlatformLoginRouteImport } from './routes/platform/login'
import { Route as PlatformDashboardRouteImport } from './routes/platform/dashboard'
import { Route as GGymSlugStaffLoginRouteImport } from './routes/g/$gymSlug/staff-login'
import { Route as GGymSlugSignupRouteImport } from './routes/g/$gymSlug/signup'
import { Route as GGymSlugResetPasswordRouteImport } from './routes/g/$gymSlug/reset-password'
import { Route as GGymSlugOnboardingRouteImport } from './routes/g/$gymSlug/onboarding'
import { Route as GGymSlugForgotRouteImport } from './routes/g/$gymSlug/forgot'
import { Route as GGymSlugAuthRouteImport } from './routes/g/$gymSlug/auth'
import { Route as GGymSlugAdminRouteImport } from './routes/g/$gymSlug/admin'
import { Route as GGymSlugAppRouteImport } from './routes/g/$gymSlug/_app'
import { Route as GGymSlugAppProfileRouteImport } from './routes/g/$gymSlug/_app/profile'
import { Route as GGymSlugAppNewsRouteImport } from './routes/g/$gymSlug/_app/news'
import { Route as GGymSlugAppMembershipRouteImport } from './routes/g/$gymSlug/_app/membership'
import { Route as GGymSlugAppLocationRouteImport } from './routes/g/$gymSlug/_app/location'
import { Route as GGymSlugAppHomeRouteImport } from './routes/g/$gymSlug/_app/home'
import { Route as GGymSlugAppCoachesRouteImport } from './routes/g/$gymSlug/_app/coaches'
import { Route as GGymSlugAppBookRouteImport } from './routes/g/$gymSlug/_app/book'
import { Route as GGymSlugAppProfileIndexRouteImport } from './routes/g/$gymSlug/_app/profile.index'
import { Route as GGymSlugAdminMembersIdRouteImport } from './routes/g/$gymSlug/admin.members.$id'
import { Route as GGymSlugAppProfileSettingsRouteImport } from './routes/g/$gymSlug/_app/profile.settings'
import { Route as GGymSlugAppProfileReferralRouteImport } from './routes/g/$gymSlug/_app/profile.referral'
import { Route as GGymSlugAppProfileEditRouteImport } from './routes/g/$gymSlug/_app/profile.edit'
import { Route as GGymSlugAppProfileChildrenRouteImport } from './routes/g/$gymSlug/_app/profile.children'
import { Route as GGymSlugAppProfileBookingsRouteImport } from './routes/g/$gymSlug/_app/profile.bookings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSignupRoute = PlatformSignupRouteImport.update({
  id: '/platform/signup',
  path: '/platform/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSetupRoute = PlatformSetupRouteImport.update({
  id: '/platform/setup',
  path: '/platform/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLoginRoute = PlatformLoginRouteImport.update({
  id: '/platform/login',
  path: '/platform/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformDashboardRoute = PlatformDashboardRouteImport.update({
  id: '/platform/dashboard',
  path: '/platform/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GGymSlugStaffLoginRoute = GGymSlugStaffLoginRouteImport.update({
  id: '/g/$gymSlug/staff-login',
  path: '/g/$gymSlug/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const GGymSlugSignupRoute = GGymSlugSignupRouteImport.update({
  id: '/g/$gymSlug/signup',
  path: '/g/$gymSlug/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const GGymSlugResetPasswordRoute = GGymSlugResetPasswordRouteImport.update({
  id: '/g/$gymSlug/reset-password',
  path: '/g/$gymSlug/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GGymSlugOnboardingRoute = GGymSlugOnboardingRouteImport.update({
  id: '/g/$gymSlug/onboarding',
  path: '/g/$gymSlug/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GGymSlugForgotRoute = GGymSlugForgotRouteImport.update({
  id: '/g/$gymSlug/forgot',
  path: '/g/$gymSlug/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const GGymSlugAuthRoute = GGymSlugAuthRouteImport.update({
  id: '/g/$gymSlug/auth',
  path: '/g/$gymSlug/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GGymSlugAdminRoute = GGymSlugAdminRouteImport.update({
  id: '/g/$gymSlug/admin',
  path: '/g/$gymSlug/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GGymSlugAppRoute = GGymSlugAppRouteImport.update({
  id: '/g/$gymSlug/_app',
  path: '/g/$gymSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GGymSlugAppProfileRoute = GGymSlugAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GGymSlugAppRoute,
} as any)
const GGymSlugAppNewsRoute = GGymSlugAppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => GGymSlugAppRoute,
} as any)
const GGymSlugAppMembershipRoute = GGymSlugAppMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => GGymSlugAppRoute,
} as any)
const GGymSlugAppLocationRoute = GGymSlugAppLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => GGymSlugAppRoute,
} as any)
const GGymSlugAppHomeRoute = GGymSlugAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => GGymSlugAppRoute,
} as any)
const GGymSlugAppCoachesRoute = GGymSlugAppCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => GGymSlugAppRoute,
} as any)
const GGymSlugAppBookRoute = GGymSlugAppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => GGymSlugAppRoute,
} as any)
const GGymSlugAppProfileIndexRoute = GGymSlugAppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GGymSlugAppProfileRoute,
} as any)
const GGymSlugAdminMembersIdRoute = GGymSlugAdminMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => GGymSlugAdminRoute,
} as any)
const GGymSlugAppProfileSettingsRoute =
  GGymSlugAppProfileSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => GGymSlugAppProfileRoute,
  } as any)
const GGymSlugAppProfileReferralRoute =
  GGymSlugAppProfileReferralRouteImport.update({
    id: '/referral',
    path: '/referral',
    getParentRoute: () => GGymSlugAppProfileRoute,
  } as any)
const GGymSlugAppProfileEditRoute = GGymSlugAppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => GGymSlugAppProfileRoute,
} as any)
const GGymSlugAppProfileChildrenRoute =
  GGymSlugAppProfileChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => GGymSlugAppProfileRoute,
  } as any)
const GGymSlugAppProfileBookingsRoute =
  GGymSlugAppProfileBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => GGymSlugAppProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/setup': typeof PlatformSetupRoute
  '/platform/signup': typeof PlatformSignupRoute
  '/platform/': typeof PlatformIndexRoute
  '/g/$gymSlug': typeof GGymSlugAppRouteWithChildren
  '/g/$gymSlug/admin': typeof GGymSlugAdminRouteWithChildren
  '/g/$gymSlug/auth': typeof GGymSlugAuthRoute
  '/g/$gymSlug/forgot': typeof GGymSlugForgotRoute
  '/g/$gymSlug/onboarding': typeof GGymSlugOnboardingRoute
  '/g/$gymSlug/reset-password': typeof GGymSlugResetPasswordRoute
  '/g/$gymSlug/signup': typeof GGymSlugSignupRoute
  '/g/$gymSlug/staff-login': typeof GGymSlugStaffLoginRoute
  '/g/$gymSlug/book': typeof GGymSlugAppBookRoute
  '/g/$gymSlug/coaches': typeof GGymSlugAppCoachesRoute
  '/g/$gymSlug/home': typeof GGymSlugAppHomeRoute
  '/g/$gymSlug/location': typeof GGymSlugAppLocationRoute
  '/g/$gymSlug/membership': typeof GGymSlugAppMembershipRoute
  '/g/$gymSlug/news': typeof GGymSlugAppNewsRoute
  '/g/$gymSlug/profile': typeof GGymSlugAppProfileRouteWithChildren
  '/g/$gymSlug/profile/bookings': typeof GGymSlugAppProfileBookingsRoute
  '/g/$gymSlug/profile/children': typeof GGymSlugAppProfileChildrenRoute
  '/g/$gymSlug/profile/edit': typeof GGymSlugAppProfileEditRoute
  '/g/$gymSlug/profile/referral': typeof GGymSlugAppProfileReferralRoute
  '/g/$gymSlug/profile/settings': typeof GGymSlugAppProfileSettingsRoute
  '/g/$gymSlug/admin/members/$id': typeof GGymSlugAdminMembersIdRoute
  '/g/$gymSlug/profile/': typeof GGymSlugAppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/setup': typeof PlatformSetupRoute
  '/platform/signup': typeof PlatformSignupRoute
  '/platform': typeof PlatformIndexRoute
  '/g/$gymSlug': typeof GGymSlugAppRouteWithChildren
  '/g/$gymSlug/admin': typeof GGymSlugAdminRouteWithChildren
  '/g/$gymSlug/auth': typeof GGymSlugAuthRoute
  '/g/$gymSlug/forgot': typeof GGymSlugForgotRoute
  '/g/$gymSlug/onboarding': typeof GGymSlugOnboardingRoute
  '/g/$gymSlug/reset-password': typeof GGymSlugResetPasswordRoute
  '/g/$gymSlug/signup': typeof GGymSlugSignupRoute
  '/g/$gymSlug/staff-login': typeof GGymSlugStaffLoginRoute
  '/g/$gymSlug/book': typeof GGymSlugAppBookRoute
  '/g/$gymSlug/coaches': typeof GGymSlugAppCoachesRoute
  '/g/$gymSlug/home': typeof GGymSlugAppHomeRoute
  '/g/$gymSlug/location': typeof GGymSlugAppLocationRoute
  '/g/$gymSlug/membership': typeof GGymSlugAppMembershipRoute
  '/g/$gymSlug/news': typeof GGymSlugAppNewsRoute
  '/g/$gymSlug/profile/bookings': typeof GGymSlugAppProfileBookingsRoute
  '/g/$gymSlug/profile/children': typeof GGymSlugAppProfileChildrenRoute
  '/g/$gymSlug/profile/edit': typeof GGymSlugAppProfileEditRoute
  '/g/$gymSlug/profile/referral': typeof GGymSlugAppProfileReferralRoute
  '/g/$gymSlug/profile/settings': typeof GGymSlugAppProfileSettingsRoute
  '/g/$gymSlug/admin/members/$id': typeof GGymSlugAdminMembersIdRoute
  '/g/$gymSlug/profile': typeof GGymSlugAppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/setup': typeof PlatformSetupRoute
  '/platform/signup': typeof PlatformSignupRoute
  '/platform/': typeof PlatformIndexRoute
  '/g/$gymSlug/_app': typeof GGymSlugAppRouteWithChildren
  '/g/$gymSlug/admin': typeof GGymSlugAdminRouteWithChildren
  '/g/$gymSlug/auth': typeof GGymSlugAuthRoute
  '/g/$gymSlug/forgot': typeof GGymSlugForgotRoute
  '/g/$gymSlug/onboarding': typeof GGymSlugOnboardingRoute
  '/g/$gymSlug/reset-password': typeof GGymSlugResetPasswordRoute
  '/g/$gymSlug/signup': typeof GGymSlugSignupRoute
  '/g/$gymSlug/staff-login': typeof GGymSlugStaffLoginRoute
  '/g/$gymSlug/_app/book': typeof GGymSlugAppBookRoute
  '/g/$gymSlug/_app/coaches': typeof GGymSlugAppCoachesRoute
  '/g/$gymSlug/_app/home': typeof GGymSlugAppHomeRoute
  '/g/$gymSlug/_app/location': typeof GGymSlugAppLocationRoute
  '/g/$gymSlug/_app/membership': typeof GGymSlugAppMembershipRoute
  '/g/$gymSlug/_app/news': typeof GGymSlugAppNewsRoute
  '/g/$gymSlug/_app/profile': typeof GGymSlugAppProfileRouteWithChildren
  '/g/$gymSlug/_app/profile/bookings': typeof GGymSlugAppProfileBookingsRoute
  '/g/$gymSlug/_app/profile/children': typeof GGymSlugAppProfileChildrenRoute
  '/g/$gymSlug/_app/profile/edit': typeof GGymSlugAppProfileEditRoute
  '/g/$gymSlug/_app/profile/referral': typeof GGymSlugAppProfileReferralRoute
  '/g/$gymSlug/_app/profile/settings': typeof GGymSlugAppProfileSettingsRoute
  '/g/$gymSlug/admin/members/$id': typeof GGymSlugAdminMembersIdRoute
  '/g/$gymSlug/_app/profile/': typeof GGymSlugAppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform/dashboard'
    | '/platform/login'
    | '/platform/setup'
    | '/platform/signup'
    | '/platform/'
    | '/g/$gymSlug'
    | '/g/$gymSlug/admin'
    | '/g/$gymSlug/auth'
    | '/g/$gymSlug/forgot'
    | '/g/$gymSlug/onboarding'
    | '/g/$gymSlug/reset-password'
    | '/g/$gymSlug/signup'
    | '/g/$gymSlug/staff-login'
    | '/g/$gymSlug/book'
    | '/g/$gymSlug/coaches'
    | '/g/$gymSlug/home'
    | '/g/$gymSlug/location'
    | '/g/$gymSlug/membership'
    | '/g/$gymSlug/news'
    | '/g/$gymSlug/profile'
    | '/g/$gymSlug/profile/bookings'
    | '/g/$gymSlug/profile/children'
    | '/g/$gymSlug/profile/edit'
    | '/g/$gymSlug/profile/referral'
    | '/g/$gymSlug/profile/settings'
    | '/g/$gymSlug/admin/members/$id'
    | '/g/$gymSlug/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/platform/dashboard'
    | '/platform/login'
    | '/platform/setup'
    | '/platform/signup'
    | '/platform'
    | '/g/$gymSlug'
    | '/g/$gymSlug/admin'
    | '/g/$gymSlug/auth'
    | '/g/$gymSlug/forgot'
    | '/g/$gymSlug/onboarding'
    | '/g/$gymSlug/reset-password'
    | '/g/$gymSlug/signup'
    | '/g/$gymSlug/staff-login'
    | '/g/$gymSlug/book'
    | '/g/$gymSlug/coaches'
    | '/g/$gymSlug/home'
    | '/g/$gymSlug/location'
    | '/g/$gymSlug/membership'
    | '/g/$gymSlug/news'
    | '/g/$gymSlug/profile/bookings'
    | '/g/$gymSlug/profile/children'
    | '/g/$gymSlug/profile/edit'
    | '/g/$gymSlug/profile/referral'
    | '/g/$gymSlug/profile/settings'
    | '/g/$gymSlug/admin/members/$id'
    | '/g/$gymSlug/profile'
  id:
    | '__root__'
    | '/'
    | '/platform/dashboard'
    | '/platform/login'
    | '/platform/setup'
    | '/platform/signup'
    | '/platform/'
    | '/g/$gymSlug/_app'
    | '/g/$gymSlug/admin'
    | '/g/$gymSlug/auth'
    | '/g/$gymSlug/forgot'
    | '/g/$gymSlug/onboarding'
    | '/g/$gymSlug/reset-password'
    | '/g/$gymSlug/signup'
    | '/g/$gymSlug/staff-login'
    | '/g/$gymSlug/_app/book'
    | '/g/$gymSlug/_app/coaches'
    | '/g/$gymSlug/_app/home'
    | '/g/$gymSlug/_app/location'
    | '/g/$gymSlug/_app/membership'
    | '/g/$gymSlug/_app/news'
    | '/g/$gymSlug/_app/profile'
    | '/g/$gymSlug/_app/profile/bookings'
    | '/g/$gymSlug/_app/profile/children'
    | '/g/$gymSlug/_app/profile/edit'
    | '/g/$gymSlug/_app/profile/referral'
    | '/g/$gymSlug/_app/profile/settings'
    | '/g/$gymSlug/admin/members/$id'
    | '/g/$gymSlug/_app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlatformDashboardRoute: typeof PlatformDashboardRoute
  PlatformLoginRoute: typeof PlatformLoginRoute
  PlatformSetupRoute: typeof PlatformSetupRoute
  PlatformSignupRoute: typeof PlatformSignupRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  GGymSlugAppRoute: typeof GGymSlugAppRouteWithChildren
  GGymSlugAdminRoute: typeof GGymSlugAdminRouteWithChildren
  GGymSlugAuthRoute: typeof GGymSlugAuthRoute
  GGymSlugForgotRoute: typeof GGymSlugForgotRoute
  GGymSlugOnboardingRoute: typeof GGymSlugOnboardingRoute
  GGymSlugResetPasswordRoute: typeof GGymSlugResetPasswordRoute
  GGymSlugSignupRoute: typeof GGymSlugSignupRoute
  GGymSlugStaffLoginRoute: typeof GGymSlugStaffLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/signup': {
      id: '/platform/signup'
      path: '/platform/signup'
      fullPath: '/platform/signup'
      preLoaderRoute: typeof PlatformSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/setup': {
      id: '/platform/setup'
      path: '/platform/setup'
      fullPath: '/platform/setup'
      preLoaderRoute: typeof PlatformSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/login': {
      id: '/platform/login'
      path: '/platform/login'
      fullPath: '/platform/login'
      preLoaderRoute: typeof PlatformLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/dashboard': {
      id: '/platform/dashboard'
      path: '/platform/dashboard'
      fullPath: '/platform/dashboard'
      preLoaderRoute: typeof PlatformDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$gymSlug/staff-login': {
      id: '/g/$gymSlug/staff-login'
      path: '/g/$gymSlug/staff-login'
      fullPath: '/g/$gymSlug/staff-login'
      preLoaderRoute: typeof GGymSlugStaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$gymSlug/signup': {
      id: '/g/$gymSlug/signup'
      path: '/g/$gymSlug/signup'
      fullPath: '/g/$gymSlug/signup'
      preLoaderRoute: typeof GGymSlugSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$gymSlug/reset-password': {
      id: '/g/$gymSlug/reset-password'
      path: '/g/$gymSlug/reset-password'
      fullPath: '/g/$gymSlug/reset-password'
      preLoaderRoute: typeof GGymSlugResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$gymSlug/onboarding': {
      id: '/g/$gymSlug/onboarding'
      path: '/g/$gymSlug/onboarding'
      fullPath: '/g/$gymSlug/onboarding'
      preLoaderRoute: typeof GGymSlugOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$gymSlug/forgot': {
      id: '/g/$gymSlug/forgot'
      path: '/g/$gymSlug/forgot'
      fullPath: '/g/$gymSlug/forgot'
      preLoaderRoute: typeof GGymSlugForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$gymSlug/auth': {
      id: '/g/$gymSlug/auth'
      path: '/g/$gymSlug/auth'
      fullPath: '/g/$gymSlug/auth'
      preLoaderRoute: typeof GGymSlugAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$gymSlug/admin': {
      id: '/g/$gymSlug/admin'
      path: '/g/$gymSlug/admin'
      fullPath: '/g/$gymSlug/admin'
      preLoaderRoute: typeof GGymSlugAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$gymSlug/_app': {
      id: '/g/$gymSlug/_app'
      path: '/g/$gymSlug'
      fullPath: '/g/$gymSlug'
      preLoaderRoute: typeof GGymSlugAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$gymSlug/_app/profile': {
      id: '/g/$gymSlug/_app/profile'
      path: '/profile'
      fullPath: '/g/$gymSlug/profile'
      preLoaderRoute: typeof GGymSlugAppProfileRouteImport
      parentRoute: typeof GGymSlugAppRoute
    }
    '/g/$gymSlug/_app/news': {
      id: '/g/$gymSlug/_app/news'
      path: '/news'
      fullPath: '/g/$gymSlug/news'
      preLoaderRoute: typeof GGymSlugAppNewsRouteImport
      parentRoute: typeof GGymSlugAppRoute
    }
    '/g/$gymSlug/_app/membership': {
      id: '/g/$gymSlug/_app/membership'
      path: '/membership'
      fullPath: '/g/$gymSlug/membership'
      preLoaderRoute: typeof GGymSlugAppMembershipRouteImport
      parentRoute: typeof GGymSlugAppRoute
    }
    '/g/$gymSlug/_app/location': {
      id: '/g/$gymSlug/_app/location'
      path: '/location'
      fullPath: '/g/$gymSlug/location'
      preLoaderRoute: typeof GGymSlugAppLocationRouteImport
      parentRoute: typeof GGymSlugAppRoute
    }
    '/g/$gymSlug/_app/home': {
      id: '/g/$gymSlug/_app/home'
      path: '/home'
      fullPath: '/g/$gymSlug/home'
      preLoaderRoute: typeof GGymSlugAppHomeRouteImport
      parentRoute: typeof GGymSlugAppRoute
    }
    '/g/$gymSlug/_app/coaches': {
      id: '/g/$gymSlug/_app/coaches'
      path: '/coaches'
      fullPath: '/g/$gymSlug/coaches'
      preLoaderRoute: typeof GGymSlugAppCoachesRouteImport
      parentRoute: typeof GGymSlugAppRoute
    }
    '/g/$gymSlug/_app/book': {
      id: '/g/$gymSlug/_app/book'
      path: '/book'
      fullPath: '/g/$gymSlug/book'
      preLoaderRoute: typeof GGymSlugAppBookRouteImport
      parentRoute: typeof GGymSlugAppRoute
    }
    '/g/$gymSlug/_app/profile/': {
      id: '/g/$gymSlug/_app/profile/'
      path: '/'
      fullPath: '/g/$gymSlug/profile/'
      preLoaderRoute: typeof GGymSlugAppProfileIndexRouteImport
      parentRoute: typeof GGymSlugAppProfileRoute
    }
    '/g/$gymSlug/admin/members/$id': {
      id: '/g/$gymSlug/admin/members/$id'
      path: '/members/$id'
      fullPath: '/g/$gymSlug/admin/members/$id'
      preLoaderRoute: typeof GGymSlugAdminMembersIdRouteImport
      parentRoute: typeof GGymSlugAdminRoute
    }
    '/g/$gymSlug/_app/profile/settings': {
      id: '/g/$gymSlug/_app/profile/settings'
      path: '/settings'
      fullPath: '/g/$gymSlug/profile/settings'
      preLoaderRoute: typeof GGymSlugAppProfileSettingsRouteImport
      parentRoute: typeof GGymSlugAppProfileRoute
    }
    '/g/$gymSlug/_app/profile/referral': {
      id: '/g/$gymSlug/_app/profile/referral'
      path: '/referral'
      fullPath: '/g/$gymSlug/profile/referral'
      preLoaderRoute: typeof GGymSlugAppProfileReferralRouteImport
      parentRoute: typeof GGymSlugAppProfileRoute
    }
    '/g/$gymSlug/_app/profile/edit': {
      id: '/g/$gymSlug/_app/profile/edit'
      path: '/edit'
      fullPath: '/g/$gymSlug/profile/edit'
      preLoaderRoute: typeof GGymSlugAppProfileEditRouteImport
      parentRoute: typeof GGymSlugAppProfileRoute
    }
    '/g/$gymSlug/_app/profile/children': {
      id: '/g/$gymSlug/_app/profile/children'
      path: '/children'
      fullPath: '/g/$gymSlug/profile/children'
      preLoaderRoute: typeof GGymSlugAppProfileChildrenRouteImport
      parentRoute: typeof GGymSlugAppProfileRoute
    }
    '/g/$gymSlug/_app/profile/bookings': {
      id: '/g/$gymSlug/_app/profile/bookings'
      path: '/bookings'
      fullPath: '/g/$gymSlug/profile/bookings'
      preLoaderRoute: typeof GGymSlugAppProfileBookingsRouteImport
      parentRoute: typeof GGymSlugAppProfileRoute
    }
  }
}

interface GGymSlugAppProfileRouteChildren {
  GGymSlugAppProfileBookingsRoute: typeof GGymSlugAppProfileBookingsRoute
  GGymSlugAppProfileChildrenRoute: typeof GGymSlugAppProfileChildrenRoute
  GGymSlugAppProfileEditRoute: typeof GGymSlugAppProfileEditRoute
  GGymSlugAppProfileReferralRoute: typeof GGymSlugAppProfileReferralRoute
  GGymSlugAppProfileSettingsRoute: typeof GGymSlugAppProfileSettingsRoute
  GGymSlugAppProfileIndexRoute: typeof GGymSlugAppProfileIndexRoute
}

const GGymSlugAppProfileRouteChildren: GGymSlugAppProfileRouteChildren = {
  GGymSlugAppProfileBookingsRoute: GGymSlugAppProfileBookingsRoute,
  GGymSlugAppProfileChildrenRoute: GGymSlugAppProfileChildrenRoute,
  GGymSlugAppProfileEditRoute: GGymSlugAppProfileEditRoute,
  GGymSlugAppProfileReferralRoute: GGymSlugAppProfileReferralRoute,
  GGymSlugAppProfileSettingsRoute: GGymSlugAppProfileSettingsRoute,
  GGymSlugAppProfileIndexRoute: GGymSlugAppProfileIndexRoute,
}

const GGymSlugAppProfileRouteWithChildren =
  GGymSlugAppProfileRoute._addFileChildren(GGymSlugAppProfileRouteChildren)

interface GGymSlugAppRouteChildren {
  GGymSlugAppBookRoute: typeof GGymSlugAppBookRoute
  GGymSlugAppCoachesRoute: typeof GGymSlugAppCoachesRoute
  GGymSlugAppHomeRoute: typeof GGymSlugAppHomeRoute
  GGymSlugAppLocationRoute: typeof GGymSlugAppLocationRoute
  GGymSlugAppMembershipRoute: typeof GGymSlugAppMembershipRoute
  GGymSlugAppNewsRoute: typeof GGymSlugAppNewsRoute
  GGymSlugAppProfileRoute: typeof GGymSlugAppProfileRouteWithChildren
}

const GGymSlugAppRouteChildren: GGymSlugAppRouteChildren = {
  GGymSlugAppBookRoute: GGymSlugAppBookRoute,
  GGymSlugAppCoachesRoute: GGymSlugAppCoachesRoute,
  GGymSlugAppHomeRoute: GGymSlugAppHomeRoute,
  GGymSlugAppLocationRoute: GGymSlugAppLocationRoute,
  GGymSlugAppMembershipRoute: GGymSlugAppMembershipRoute,
  GGymSlugAppNewsRoute: GGymSlugAppNewsRoute,
  GGymSlugAppProfileRoute: GGymSlugAppProfileRouteWithChildren,
}

const GGymSlugAppRouteWithChildren = GGymSlugAppRoute._addFileChildren(
  GGymSlugAppRouteChildren,
)

interface GGymSlugAdminRouteChildren {
  GGymSlugAdminMembersIdRoute: typeof GGymSlugAdminMembersIdRoute
}

const GGymSlugAdminRouteChildren: GGymSlugAdminRouteChildren = {
  GGymSlugAdminMembersIdRoute: GGymSlugAdminMembersIdRoute,
}

const GGymSlugAdminRouteWithChildren = GGymSlugAdminRoute._addFileChildren(
  GGymSlugAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlatformDashboardRoute: PlatformDashboardRoute,
  PlatformLoginRoute: PlatformLoginRoute,
  PlatformSetupRoute: PlatformSetupRoute,
  PlatformSignupRoute: PlatformSignupRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  GGymSlugAppRoute: GGymSlugAppRouteWithChildren,
  GGymSlugAdminRoute: GGymSlugAdminRouteWithChildren,
  GGymSlugAuthRoute: GGymSlugAuthRoute,
  GGymSlugForgotRoute: GGymSlugForgotRoute,
  GGymSlugOnboardingRoute: GGymSlugOnboardingRoute,
  GGymSlugResetPasswordRoute: GGymSlugResetPasswordRoute,
  GGymSlugSignupRoute: GGymSlugSignupRoute,
  GGymSlugStaffLoginRoute: GGymSlugStaffLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
